import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import { configDotenv } from "dotenv";
import { ConnectDB } from "./DB/data-base";
import category from "../src/Food/Router/category-router";
import food from "../src/Food/Router/food-router";
import burtguuleh from "./burtguuleh/Router-Sign-In/signupRouter";
import signinrouter from "./User/userRouter/userRouter";
import checkPasswords from "../src/goAdmin/goRouters/goRouters";
import getorder from "../src/Order/Router/orderRouter";
const app = express();
app.use(bodyParser.json());
app.use(cors());
configDotenv();
ConnectDB();
const port = process.env.PORT;
app.use("/goadmin", checkPasswords);
app.use("/food", food);
app.use("/api", category);
app.use("/burtguuleh", burtguuleh);
app.use("/signin", signinrouter);
app.use("/orders", getorder);
app.listen(port, () => {
  console.log(`port is runing at:>${port}`);
});
